Updated KillProgram method. Closed #30
TopAcademy2022/user-monitoring-gui pull request #52
Opened 2024-03-23 18:24 UTC by cany8042

2024-03-23 18:32 UTC, xsasx9 approved these changes, later dismissed

2024-03-23 18:36 UTC, TopAcademy2022 approved these changes, later dismissed

2024-03-25 15:44 UTC, HecuseS requested changes

2024-03-25 15:44 UTC, HecuseS commented on user-monitoring-gui/Services/RunProgramReader.cs
Revert CheckRunProgram method.

2024-03-25 15:44 UTC, HecuseS commented on user-monitoring-gui/Services/RunProgramReader.cs
> +                        public bool KillProgram( string programName )  /*метод для завершения указанного программного процесса.*/
Remove spaces!

2024-03-25 16:00 UTC, Andrey31ts approved these changes, later dismissed

2024-03-25 16:02 UTC, London3149-train submitted a review, later dismissed

2024-03-25 17:51 UTC, SugarSalt9 approved these changes, later dismissed

2024-03-25 17:57 UTC, Mi-stik31 submitted a review, later dismissed

2024-03-27 18:10 UTC, TopAcademy2022 approved these changes

2024-03-27 18:11 UTC, HecuseS approved these changes

2024-03-27 18:13 UTC, London3149-train approved these changes

2024-03-27 18:14 UTC, Mi-stik31 approved these changes

2024-03-27 18:17 UTC, Andrey31ts approved these changes

2024-03-29 16:46 UTC, SugarSalt9 approved these changes

2024-03-29 16:54 UTC, xsasx9 approved these changes

2024-03-29 17:05 UTC, merged