Implemented the LoadProgramBanList method. Closed #49
TopAcademy2022/user-monitoring-gui pull request #57
Opened 2024-03-29 18:25 UTC by London3149-train

2024-03-30 18:53 UTC, TopAcademy2022 requested changes
Why main (HEAD) files was edited?

2024-03-30 18:53 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ConsoleUserInterface.cs
Revert this file.

2024-03-30 18:53 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/Interfaces/IServerRequest.cs
Revert this file to main (HEAD).

2024-03-30 18:53 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/RunProgramReader.cs
Revert this file.

2024-04-01 14:56 UTC, HecuseS approved these changes, later dismissed

2024-04-01 15:52 UTC, cany8042 submitted a review, later dismissed

2024-04-01 18:01 UTC, Andrey31ts submitted a review, later dismissed

2024-04-03 15:52 UTC, cany8042 approved these changes, later dismissed

2024-04-03 15:58 UTC, TopAcademy2022 requested changes

2024-04-03 15:58 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +
Remove space.

2024-04-03 15:58 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +
Remove space.

2024-04-03 15:58 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +                var byat = this._serverReqwest.LoadData( programBanList.GetType()).GetData();
Rename variable.

2024-04-03 16:04 UTC, HecuseS submitted a review, later dismissed

2024-04-03 16:06 UTC, cany8042 approved these changes

2024-04-03 16:07 UTC, HecuseS approved these changes

2024-04-03 16:08 UTC, xs887z approved these changes

2024-04-03 16:09 UTC, SugarSalt9 approved these changes

2024-04-03 16:10 UTC, Andrey31ts approved these changes

2024-04-03 16:18 UTC, Mi-stik31 approved these changes

2024-04-03 16:19 UTC, TopAcademy2022 approved these changes

2024-04-03 16:19 UTC, merged