Implemented the SaveProgramBanList method. Closed #17
TopAcademy2022/user-monitoring-gui pull request #60
Opened 2024-04-01 16:27 UTC by Andrey31ts

2024-04-01 16:28 UTC, cany8042 submitted a review, later dismissed

2024-04-01 16:52 UTC, TopAcademy2022 requested changes

2024-04-01 16:52 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +    public class ProgramBanListService:IProgramBanListService
Add spaces before ":" symbol.

2024-04-01 16:52 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +
Remove this line.

2024-04-01 16:52 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +   private IServerRequest _serverReqwest;
Add tabs.

2024-04-01 16:52 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +        public bool Save(ProgramBanList programBanList, DataStorageArea dataStorageArea)
Add space.

2024-04-01 16:52 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
Update IProgramBanListService.

2024-04-01 18:22 UTC, TopAcademy2022 approved these changes, later dismissed

2024-04-02 09:29 UTC, HecuseS requested changes

2024-04-02 09:29 UTC, HecuseS commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +	private IServerRequest _serverReqwest;
replace the word "Reqwest" with the correct spelling - Request

2024-04-02 09:29 UTC, HecuseS commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +
Delite line

2024-04-03 15:56 UTC, TopAcademy2022 requested changes

2024-04-03 15:56 UTC, TopAcademy2022 commented on user-monitoring-gui/Services/ProgramBanListService.cs
> +   public bool Load()
Add space.

2024-04-03 15:57 UTC, HecuseS submitted a review, later dismissed

2024-04-03 16:03 UTC, TopAcademy2022 approved these changes, later dismissed

2024-04-03 16:05 UTC, London3149-train approved these changes, later dismissed

2024-04-03 16:07 UTC, cany8042 approved these changes, later dismissed

2024-04-03 16:07 UTC, HecuseS approved these changes, later dismissed

2024-04-03 16:08 UTC, xs887z approved these changes, later dismissed

2024-04-03 16:08 UTC, SugarSalt9 approved these changes, later dismissed

2024-04-03 16:18 UTC, Mi-stik31 approved these changes, later dismissed

2024-04-03 16:32 UTC, xs887z approved these changes

2024-04-03 16:34 UTC, xs887z approved these changes, later dismissed

2024-04-03 16:39 UTC, HecuseS approved these changes

2024-04-03 16:40 UTC, TopAcademy2022 approved these changes

2024-04-03 16:40 UTC, xs887z approved these changes

2024-04-03 16:41 UTC, Mi-stik31 approved these changes

2024-04-03 16:41 UTC, cany8042 approved these changes

2024-04-03 16:41 UTC, London3149-train approved these changes

2024-04-03 16:42 UTC, SugarSalt9 approved these changes

2024-04-03 16:42 UTC, merged