Added documentation ProgramBanList. Closed #56
TopAcademy2022/user-monitoring-gui pull request #66
Opened 2024-04-08 15:53 UTC by SugarSalt9

2024-04-08 16:01 UTC, TopAcademy2022 requested changes

2024-04-08 16:01 UTC, TopAcademy2022 commented on user-monitoring-gui/Models/ProgramBanList.cs
>          private List<string> _programBanList;
Add documentation.

2024-04-08 16:01 UTC, TopAcademy2022 commented on user-monitoring-gui/Models/ProgramBanList.cs
> +         * @param programName The name of the program to add.
Add "[in]" to param section.

2024-04-08 16:01 UTC, TopAcademy2022 commented on user-monitoring-gui/Models/ProgramBanList.cs
> +        public void AddProgram( string programName )
Remove spaces.

2024-04-08 16:01 UTC, TopAcademy2022 commented on user-monitoring-gui/Models/ProgramBanList.cs
> +         * @param programName The name of the program to remove.
See above.

2024-04-08 16:01 UTC, TopAcademy2022 commented on user-monitoring-gui/Models/ProgramBanList.cs
> +        public void RemoveProgram( string programName )
Remove spaces.

2024-04-08 16:04 UTC, HecuseS approved these changes

2024-04-12 16:17 UTC, xs887z approved these changes

2024-05-29 16:08 UTC, cany8042 approved these changes

2024-12-24 16:53 UTC, closed without merging